// Builds dist/ — copies static files and injects Supabase config from environment.
const fs = require("fs");
const path = require("path");

// Load .env for local builds (no dependencies)
const envFile = path.join(__dirname, ".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
}

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error("ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.");
  console.error("  Local:   copy .env.example to .env and fill in the values");
  console.error("  Vercel:  Project -> Settings -> Environment Variables");
  process.exit(1);
}

const root = __dirname;
const out = path.join(root, "dist");

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

for (const f of ["index.html", "styles.css", "app.js"]) {
  fs.copyFileSync(path.join(root, f), path.join(out, f));
}
fs.cpSync(path.join(root, "vendor"), path.join(out, "vendor"), { recursive: true });

fs.writeFileSync(
  path.join(out, "config.js"),
  "// Generated by build.js - do not edit (values come from environment)\n" +
    "window.ENV = {\n" +
    `  SUPABASE_URL: ${JSON.stringify(url)},\n` +
    `  SUPABASE_ANON_KEY: ${JSON.stringify(key)},\n` +
    "};\n"
);

console.log("Built dist/ with Supabase config injected from environment.");
